INSERT INTO inventory (Id, Niveau, Name, Description, Active)
VALUES
(1, 'Novice', 'CompTIA ITF+', 'blablabla', 1),
(2, 'Novice', 'Google IT Cert', 'blablabla', 1),
(3, 'Novice', 'CompTIA A+', 'blablabla', 1),
(4, 'Intermediate', 'CompTIA Network+', 'blablabla', 1),
(5, 'Intermediate', 'CompTIA Security+', 'blablabla', 1),
(6, 'Intermediate', 'CompTIA Server+', 'blablabla', 1),
(7, 'Intermediate', 'CCNA', 'blablabla', 1),
(8, 'Intermediate', 'CCIA', 'blablabla', 1),
(9, 'Intermediate', 'CEH', 'blablabla', 1),
(10, 'Intermediate', 'CHFI', 'blablabla', 1),
(11, 'Intermediate', 'GCIH', 'blablabla', 1),
(12, 'Intermediate', 'GISP', 'blablabla', 1),
(13, 'Intermediate', 'GSEC', 'blablabla', 1),
(14, 'Intermediate', 'MCSA: Windows Server', 'blablabla', 1),
(15, 'Advanced', 'CompTIA CySA+', 'blablabla', 1),
(16, 'Advanced', 'CCSK', 'blablabla', 1),
(17, 'Advanced', 'CCNP', 'blablabla', 1),
(18, 'Advanced', 'CSSLP', 'blablabla', 1),
(19, 'Advanced', 'GSLC', 'blablabla', 1),
(20, 'Advanced', 'GCED', 'blablabla', 1),
(21, 'Advanced', 'CompTIA Pentest+', 'blablabla', 1),
(22, 'Advanced', 'CCDP', 'blablabla', 1),
(23, 'Advanced', 'CISA', 'blablabla', 1),
(24, 'Advanced', 'MCSE: Core Infrastructure', 'blablabla', 1),
(25, 'Expert', 'CompTIA CASP+', 'blablabla', 1),
(26, 'Expert', 'CCIE', 'blablabla', 1),
(27, 'Expert', 'SCYBER', 'blablabla', 1),
(28, 'Expert', 'CGEIT', 'blablabla', 1),
(29, 'Expert', 'CISM', 'blablabla', 1),
(30, 'Expert', 'CISSP', 'blablabla', 1),
(31, 'Expert', 'CPTE', 'blablabla', 1);
